# fly.toml app configuration file generated for ai-stack-junkikanda on 2025-05-27T13:30:28+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-stack-junkikanda'
primary_region = 'nrt'
kill_signal = 'SIGTERM'
kill_timeout = '30s'

[experimental]
  auto_rollback = true

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'rolling'
  max_unavailable = 0.0

[env]
  HEALTH_CHECK_PORT = '8080'
  PYTHONUNBUFFERED = '1'
  RUN_BATCH_ON_START = 'false'
  TZ = 'Asia/Tokyo'

[[mounts]]
  source = 'ai_stack_data'
  destination = '/app/data'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = false
  min_machines_running = 0

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'requests'
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '2m0s'
    method = 'GET'
    path = '/health'
    protocol = 'http'
    tls_skip_verify = false

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
