name: Daily Cost Report

on:
  schedule:
    - cron: '0 15 * * *'  # 毎日15:00 UTC（日本時間0:00）
  workflow_dispatch:

jobs:
  cost-report:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: Trigger daily cost report
        run: |
          echo "Triggering daily cost report..."
          
          # 直接APIを呼び出す（マシンは自動起動）
          response=$(curl -s -w "\n%{http_code}" -X POST https://ai-stack-junkikanda.fly.dev/finops/daily-report)
          
          # レスポンスを分離
          body=$(echo "$response" | head -n -1)
          http_code=$(echo "$response" | tail -n 1)
          
          echo "Response: $body"
          echo "HTTP Code: $http_code"
          
          # エラーチェック
          if [ "$http_code" != "200" ]; then
            echo "Error: Failed to generate report (HTTP $http_code)"
            exit 1
          fi
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}